#!/bin/bash
echo -en '\nRefreshing edge upnp library files for github...'
cp ~/lua_projects/upnp/hub/config.yml ~/lua_projects/upnp/edge_upnp/hubpackage/config.yml
cp ~/lua_projects/upnp/hub/src/init.lua ~/lua_projects/upnp/edge_upnp/hubpackage/src/init.lua
cp ~/lua_projects/upnp/hub/src/command_handlers.lua ~/lua_projects/upnp/edge_upnp/hubpackage/src/command_handlers.lua
cp ~/lua_projects/upnp/hub/src/UPnP/init.lua ~/lua_projects/upnp/edge_upnp/hubpackage/src/UPnP/init.lua
cp ~/lua_projects/upnp/hub/src/UPnP/watcher.lua ~/lua_projects/upnp/edge_upnp/hubpackage/src/UPnP/watcher.lua
cp ~/lua_projects/upnp/hub/src/UPnP/eventing.lua ~/lua_projects/upnp/edge_upnp/hubpackage/src/UPnP/eventing.lua
cp ~/lua_projects/upnp/hub/src/UPnP/xmlparse.lua ~/lua_projects/upnp/edge_upnp/hubpackage/src/UPnP/xmlparse.lua
cp ~/lua_projects/upnp/hub/src/UPnP/description.lua ~/lua_projects/upnp/edge_upnp/hubpackage/src/UPnP/description.lua
cp ~/lua_projects/upnp/hub/src/UPnP/control.lua ~/lua_projects/upnp/edge_upnp/hubpackage/src/UPnP/control.lua
cp ~/lua_projects/upnp/hub/src/UPnP/upnpcommon.lua ~/lua_projects/upnp/edge_upnp/hubpackage/src/UPnP/upnpcommon.lua
cp ~/lua_projects/upnp/hub/src/UPnP/printdesc.lua ~/lua_projects/upnp/edge_upnp/hubpackage/src/UPnP/printdesc.lua
cp ~/lua_projects/upnp/hub/profiles/genericupnp.yaml ~/lua_projects/upnp/edge_upnp/hubpackage/profiles/genericupnp.yaml
cp ~/lua_projects/upnp/hub/capabilities/upnpseqnum.yaml ~/lua_projects/upnp/edge_upnp/hubpackage/capabilities/upnpseqnum.yaml
cp ~/lua_projects/upnp/hub/capabilities/upnpexpiration.yaml ~/lua_projects/upnp/edge_upnp/hubpackage/capabilities/upnpexpiration.yaml
cp ~/lua_projects/upnp/hub/capabilities/upnpurn.yaml ~/lua_projects/upnp/edge_upnp/hubpackage/capabilities/upnpurn.yaml
cp ~/lua_projects/upnp/hub/capabilities/upnpuuid.yaml ~/lua_projects/upnp/edge_upnp/hubpackage/capabilities/upnpuuid.yaml
cp ~/lua_projects/upnp/hub/capabilities/upnpmodel.yaml ~/lua_projects/upnp/edge_upnp/hubpackage/capabilities/upnpmodel.yaml
echo -e 'DONE\n'
echo 'Updating github'
git pull origin main
git add --all
git commit -m 'refresh'
git push origin main
